export const FETCH_PARKING_LOT_REQUEST = "FETCH_PARKING_LOT_REQUEST";
export const PARKING_LOT_SUCCESS = "PARKING_LOT_SUCCESS";
export const PARKING_LOT_FAILURE = "PARKING_LOT_FAILURE";

export const VEHICLE_CHECKOUT_REQUEST = "VEHICLE_CHECKOUT_REQUEST";
export const VEHICLE_CHECKOUT_SUCCESS = "VEHICLE_CHECKOUT_SUCCESS";
export const VEHICLE_CHECKOUT_FAILURE = "VEHICLE_CHECKOUT_FAILURE";

export const VEHICLE_CHECKIN_REQUEST = "VEHICLE_CHECKIN_REQUEST";
export const VEHICLE_CHECKIN_SUCCESS = "VEHICLE_CHECKIN_SUCCESS";
export const VEHICLE_CHECKIN_FAILURE = "VEHICLE_CHECKIN_FAILURE";